# -- stackhawk configuration for express_app --
app:
  # -- An applicationId obtained from the StackHawk platform. --
  applicationId: 3159de2e-2aae-44c2-86dc-b9c4474ec717 # (required)
  # -- The environment for the applicationId defined in the StackHawk platform. --
  env: Production # (required)
  # -- The url of your application to scan --
  host: https://frosty-dew-1529.section.app # (required)


# -- Customized Configuration for GraphQL/SOAP/OpenAPI, add here --
  # Configuration Docs: https://docs.stackhawk.com/hawkscan/configuration/

# -- If Authenticated Scanning is needed, add here --
  # Authenticated Scanning Docs: https://docs.stackhawk.com/hawkscan/authenticated-scanning.html
  # Authenticated Scanning Repo: https://github.com/kaakaww/scan-configuration/tree/main/Authentication

# -- Help Section --
  # Docs: https://docs.stackhawk.com/
  # Contact Support: support@stackhawk.com
